version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - Cweili
  ignore:
  - dependency-name: find-my-way
    versions:
    - 4.0.0
